### ISSUE TITLE
Increase display size of Token

### ISSUE THREAD

**Issue by jackouille-ch** [netniV/plugin_tokenauth#2]
By default we get the following view:
![image](https://user-images.githubusercontent.com/35721406/44106054-d073eb5c-9ff3-11e8-8169-85a1b9015d4d.png)

HTML commands is right:
<textarea class='ui-state-default ui-corner-all' aria-multiline='true' cols='80' rows='5' id='token' name='token'>

But maybe selected font changes the view. You could maybe use Courrier for it or increase cols to 120 and increase rows to 20, we have the full screen left.

**Comment by netniV** [comment]
I have now increased the display size, but will have to check what it looks like on the mobile to see if I'm happy with it.  Found that there is actually an issue with the underlying form_text_aarea that doesn't apply the class a field has defined for it, so that's a separate issue for me to raise.

Instead, I've had to manually override the style with a style block directly on the form but it works for now.
