### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by jackouille-ch** [netniV/plugin_tokenauth#3]
Update each hour the token because after 24 hours, token expires despite account is continuously viewing graphs.

**Comment by netniV** [comment]
Once you are logged into Cacti, it is the Cacti settings that determine when a session expires and needs to be logged in again.  If you attempt to auth the token and it fails due to a different day, you simply generate another token.

Whilst the account is actively viewing graphs and the cacti session hasn't expired, you will be still logged in.  If your session expires, this is like you've been manually signed out, so you need to sign in again, ergo, auth with a token.
